platform :ios, ‘7.0’
pod "AFNetworking", "~> 2.0”
pod 'MJRefresh', '~> 3.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'ShareSDK3'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat’